defaults:
  - config
  - protocol: dmc_proprio
  - model_size: size1m
  - _self_

env:
  backend: dm_control
  name: walker
  task: walk

networks:
  # The walker observation keys in sorted order: height, orientations,
  # velocity.
  decoder_event_dims: [1, 14, 9]

logger:
  output_plot: dreamer_v3_dmc_walker.png
  metrics_jsonl: dreamer_v3_dmc_walker.jsonl

benchmark:
  minimum_final_median_return: 900.0
